# Generated by Django 4.0.2 on 2022-02-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('channel', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=4)),
                ('os', models.CharField(choices=[('ios', 'ios'), ('android', 'android')], max_length=7)),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('installs', models.IntegerField()),
                ('spend', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
        ),
    ]
