# Generated by Django 4.0.2 on 2022-02-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancemetrics',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='spend',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
